version: "3"
services:
    express-app:
        build:
            context: .
        ports:
            - "8002:5000"
        environment:
            - PORT=5000
        volumes:
            - ./:/app
            - /app/node_modules
    