version: "3"
services:
    express-app:
        build: .
        ports:
            - "8000:5000"
        environment:
            - PORT=5000
        volumes:
            - ./:/app
            - /app/node_modules
    